"""Thematic Analysis sub-tab."""

from dash import dcc, html, dash_table
import dash_bootstrap_components as dbc

from dashboard.charts.template import CHART_CONFIG
from dashboard.components.stat_card import stat_card
from dashboard.components.table_styles import ENRICHED_TABLE_STYLES
from dashboard.config import REGISTER_SOURCE_ICON, DERIVED_FIELD_ICON
from dashboard.data.registry import (
    _ALL_DATASET_OPTIONS, _ALL_PROVIDER_OPTIONS, _ALL_INSTITUTION_OPTIONS, _ALL_TRE_OPTIONS,
)
from dashboard.data.thematic import (
    THEMATIC_DATA_AVAILABLE, THEMATIC_NARRATIVE, THEMATIC_PROJECT_COUNT,
    _THEMATIC_DOMAIN_OPTIONS, _THEMATIC_DOMAIN_COUNT_OPTIONS,
    _THEMATIC_LINKAGE_OPTIONS, _THEMATIC_PURPOSE_OPTIONS,
)


_thematic_methodology_md = """
**Model:** Claude Opus 4.6 (`claude-opus-4-6`) via the Anthropic API with structured
JSON output and `temperature=0` for deterministic classification.

**Input:** Each project's title and its listed datasets are provided to the model
together. Both fields inform all three classification layers — titles provide the
research question while datasets reveal the data domains and linkage scope.

**Batch processing:** Projects are classified in batches of 10-20, with automatic
retry logic for transient API failures. Results are cached locally so that
re-runs only classify new or changed projects.

**Validation:** A controlled experiment compared Opus 4.6 and Sonnet 4.6 on a
150-project stratified sample. Opus was selected as the preferred model after
manual review of disagreements.
"""

_thematic_layers_md = """
#### Layer A — Substantive Domain (1 or more per project)

Projects are assigned to one or more of 14 thematic domains based on the
research question and datasets used:

| Domain | Description |
|--------|-------------|
| Labour Market & Employment | Wages, jobs, skills demand, unemployment, gig economy |
| Business & Productivity | Firm performance, innovation, trade, enterprise zones |
| Education & Skills | Schools, universities, qualifications, pupil outcomes |
| Health & Social Care | NHS, mortality, mental health, social care interactions |
| Poverty, Inequality & Living Standards | Income distribution, deprivation, benefits, cost of living |
| Gender, Race & Ethnicity | Disparities by sex, ethnicity, or gender identity |
| Migration & Demographics | Population flows, fertility, ageing, migrant outcomes |
| Crime & Justice | Offending, victimisation, courts, policing |
| COVID-19 & Pandemic | Pandemic-specific research and data |
| Housing & Planning | Housing markets, homelessness, planning, energy in homes |
| Environment & Agriculture | Land use, farming, pollution, climate, food |
| Public Finance & Taxation | Tax policy, revenue, government expenditure |
| Data Infrastructure & Methodology | Linkage methods, data quality, statistical methodology |
| Unclear from Title | Insufficient information to classify |

&nbsp;

#### Layer B — Linkage Mode (exactly 1 per project)

Each project is assigned to one linkage mode based on the number of policy
domains its datasets span:

| Mode | Description |
|------|-------------|
| Single-Dataset | Uses only one dataset |
| Within-Domain Linkage | Links multiple datasets from the same policy domain |
| Cross-Domain Linkage | Links datasets across two or more distinct policy domains |

&nbsp;

#### Layer C — Analytical Purpose (1 or 2 per project)

Projects are classified by their primary research purpose:

| Purpose | Description |
|---------|-------------|
| Descriptive Monitoring | Measuring prevalence, trends, or patterns |
| Policy Evaluation / Impact Analysis | Evaluating a specific policy, programme, or intervention |
| Outcome Tracking | Linking an exposure or condition to a downstream outcome |
| Inequality / Disparities Analysis | Comparing outcomes across social groups |
| Life-Course / Trajectory Analysis | Tracking individuals over extended time periods |
| Methodological / Infrastructure Research | Developing or validating data linkage methods |
| Risk Prediction / Early Identification | Building risk scores or identifying at-risk subgroups |
| Service Interaction / Systems Analysis | How individuals move through public services |
"""


def build_thematic_tab():
    if THEMATIC_DATA_AVAILABLE:
        children = [
            # Section 1: Caveat banner
            dbc.Alert([
                html.Strong("Experimental Analysis"),
                " — Classifications below were generated by a large language model (Claude Opus). "
                "They are based on project titles and dataset names only, and should be treated as "
                "indicative rather than definitive. Ambiguous or terse titles may be misclassified.",
            ], color="warning", className="mb-3 mt-2"),

            # Summary stats
            dbc.Row([
                stat_card(f"{THEMATIC_PROJECT_COUNT:,}", "Projects Classified", "#2a9d8f"),
                stat_card("14", "Substantive Domains", "#264653"),
                stat_card(f"{len(_THEMATIC_LINKAGE_OPTIONS) - 1:,}", "Linkage Modes", "#457b9d"),
                stat_card("9", "Analytical Purposes", "#e76f51"),
            ], className="mb-3 g-3"),

            html.P(
                "Each project is independently classified across three layers: "
                "the substantive research domain(s), the data linkage complexity, "
                "and the analytical purpose. Projects may belong to multiple domains "
                "and may have up to two analytical purposes.",
                className="section-desc",
            ),

            # Section 2: Collapsible methods
            dbc.Accordion([
                dbc.AccordionItem(
                    dcc.Markdown(_thematic_methodology_md, style={"fontSize": "0.85rem", "lineHeight": "1.6"}),
                    title="Classification Methodology",
                ),
                dbc.AccordionItem(
                    dcc.Markdown(_thematic_layers_md, style={"fontSize": "0.85rem", "lineHeight": "1.6"}),
                    title="Layer Definitions",
                ),
                dbc.AccordionItem(
                    dcc.Markdown(THEMATIC_NARRATIVE, style={"fontSize": "0.85rem", "lineHeight": "1.6"}),
                    title="Analytical Narrative (LLM-Generated)",
                ),
            ], start_collapsed=True, className="mb-4"),

            # Section 3: Metric toggle
            dbc.Row([
                dbc.Col([
                    html.Label("Metric", className="filter-label"),
                    dcc.Dropdown(
                        id="thematic-metric-toggle",
                        options=[
                            {"label": "% of projects in year", "value": "pct"},
                            {"label": "Absolute project count", "value": "count"},
                        ],
                        value="pct",
                        clearable=False,
                    ),
                ], md=3),
            ], className="mb-3 g-2"),

            # Section 3: Domain trends
            html.H5(
                "Substantive Domains Over Time",
                className="mt-3 mb-2",
                style={"color": "#2c3e50", "fontWeight": "600"},
            ),
            html.P(
                "Projects may belong to multiple domains, so percentages sum to more than 100% per year. "
                "Click a legend entry to show/hide individual domains.",
                className="section-desc",
            ),
            dbc.Row([
                dbc.Col(html.Div(
                    dcc.Graph(id="thematic-domain-trend", config=CHART_CONFIG),
                    className="chart-wrapper",
                ), width=12),
            ]),

            # Section 4: Linkage mode trends
            html.H5(
                "Data Linkage Complexity Over Time",
                className="mt-4 mb-2",
                style={"color": "#2c3e50", "fontWeight": "600"},
            ),
            html.P(
                "Each project has exactly one linkage mode, so these shares are compositional.",
                className="section-desc",
            ),
            dbc.Row([
                dbc.Col(html.Div(
                    dcc.Graph(id="thematic-linkage-trend", config=CHART_CONFIG),
                    className="chart-wrapper",
                ), width=12),
            ]),

            # Section 5: Purpose trends
            html.H5(
                "Analytical Purpose Over Time",
                className="mt-4 mb-2",
                style={"color": "#2c3e50", "fontWeight": "600"},
            ),
            html.P(
                "Projects may have up to two purposes, so percentages can sum to slightly more than 100%.",
                className="section-desc",
            ),
            dbc.Row([
                dbc.Col(html.Div(
                    dcc.Graph(id="thematic-purpose-trend", config=CHART_CONFIG),
                    className="chart-wrapper",
                ), width=12),
            ]),

            # Section 6: Totals
            html.H5(
                "Overall Distribution",
                className="mt-4 mb-2",
                style={"color": "#2c3e50", "fontWeight": "600"},
            ),
            dbc.Row([
                dbc.Col(html.Div(
                    dcc.Graph(id="thematic-domain-totals", config=CHART_CONFIG),
                    className="chart-wrapper",
                ), md=5),
                dbc.Col(html.Div(
                    dcc.Graph(id="thematic-linkage-totals", config=CHART_CONFIG),
                    className="chart-wrapper",
                ), md=3),
                dbc.Col(html.Div(
                    dcc.Graph(id="thematic-purpose-totals", config=CHART_CONFIG),
                    className="chart-wrapper",
                ), md=4),
            ], className="g-3"),

            # Section 7: Cross-layer heatmaps
            html.H5(
                "Cross-Layer Patterns",
                className="mt-4 mb-2",
                style={"color": "#2c3e50", "fontWeight": "600"},
            ),
            html.P(
                "Cross-tabulations use the primary (first-listed) domain for each project. "
                "Only the six most common primary domains are shown.",
                className="section-desc",
            ),
            dbc.Row([
                dbc.Col(html.Div(
                    dcc.Graph(id="thematic-cross-mode-domain", config=CHART_CONFIG),
                    className="chart-wrapper",
                ), md=6),
                dbc.Col(html.Div(
                    dcc.Graph(id="thematic-cross-domain-purpose", config=CHART_CONFIG),
                    className="chart-wrapper",
                ), md=6),
            ], className="g-3 mb-4"),

            # Section 8: Enriched Register
            html.H5(
                "Enriched Register",
                className="mt-4 mb-2",
                style={"color": "#2c3e50", "fontWeight": "600"},
            ),
            html.P(
                "The Enriched Register combines the canonical DEA register (the source of truth, "
                "also accessible via the Project Explorer) with classifications and analytical fields "
                f"derived from the project descriptions. Columns sourced directly from the public "
                f"register are marked with a {REGISTER_SOURCE_ICON} icon; classifications derived "
                f"by the dashboard's analytical layer are marked with a {DERIVED_FIELD_ICON} icon.",
                className="section-desc",
            ),
            dbc.Row([
                dbc.Col([
                    html.Label("Search", className="filter-label"),
                    dbc.Input(
                        id="enriched-search",
                        placeholder="Search by project ID, title, or researcher…",
                        type="text",
                    ),
                ], md=5),
                dbc.Col([
                    html.Label("Dataset", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-dataset-filter",
                        options=_ALL_DATASET_OPTIONS,
                        value="ALL",
                        clearable=False,
                        searchable=True,
                        placeholder="All datasets",
                    ),
                ], md=3),
                dbc.Col([
                    html.Label("Source organisation", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-provider-filter",
                        options=_ALL_PROVIDER_OPTIONS,
                        value="ALL",
                        clearable=False,
                        searchable=True,
                        placeholder="All source organisations",
                    ),
                ], md=2),
                dbc.Col([
                    html.Label("Domain count", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-domain-count-filter",
                        options=_THEMATIC_DOMAIN_COUNT_OPTIONS,
                        value="ALL",
                        clearable=False,
                        searchable=False,
                    ),
                ], md=2),
            ], className="mb-2 g-2"),
            dbc.Row([
                dbc.Col([
                    html.Label("Research institution", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-institution-filter",
                        options=_ALL_INSTITUTION_OPTIONS,
                        value="ALL",
                        clearable=False,
                        searchable=True,
                        placeholder="All institutions",
                    ),
                ], md=3),
                dbc.Col([
                    html.Label("Processing environment", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-tre-filter",
                        options=_ALL_TRE_OPTIONS,
                        value="ALL",
                        clearable=False,
                        searchable=True,
                        placeholder="All processing environments",
                    ),
                ], md=2),
                dbc.Col([
                    html.Label("Domain", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-domain-filter",
                        options=_THEMATIC_DOMAIN_OPTIONS,
                        value="ALL",
                        clearable=False,
                        searchable=True,
                    ),
                ], md=2),
                dbc.Col([
                    html.Label("Linkage mode", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-linkage-filter",
                        options=_THEMATIC_LINKAGE_OPTIONS,
                        value="ALL",
                        clearable=False,
                        searchable=False,
                    ),
                ], md=2),
                dbc.Col([
                    html.Label("Analytical purpose", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-purpose-filter",
                        options=_THEMATIC_PURPOSE_OPTIONS,
                        value="ALL",
                        clearable=False,
                        searchable=True,
                    ),
                ], md=2),
                dbc.Col([
                    html.Label("Per page", className="filter-label"),
                    dcc.Dropdown(
                        id="enriched-page-size",
                        options=[{"label": str(n), "value": n} for n in [10, 20, 50, 100]],
                        value=20,
                        clearable=False,
                        searchable=False,
                    ),
                ], md=1),
            ], className="mb-2 g-2"),
            dbc.Row([
                dbc.Col(
                    dbc.Switch(
                        id="enriched-include-unclassified",
                        label="Include unclassified projects",
                        value=False,
                        className="pt-1",
                    ),
                    md=3,
                ),
                dbc.Col([
                    html.Div(
                        id="enriched-browse-count",
                        className="text-muted small",
                        style={"paddingTop": "0.35rem", "textAlign": "center"},
                    ),
                ], md=6),
                dbc.Col([
                    html.Button(
                        "Download CSV",
                        id="enriched-download-btn",
                        className="btn btn-outline-primary btn-sm w-100",
                    ),
                    dbc.Tooltip(
                        "Downloads all projects matching the current filters.",
                        target="enriched-download-btn",
                        placement="top",
                    ),
                ], md=3),
            ], className="mb-3 g-2"),
            html.Div(
                dash_table.DataTable(
                    id="enriched-register-table",
                    columns=[
                        {"name": f"{REGISTER_SOURCE_ICON} Project ID", "id": "Project ID"},
                        {"name": f"{REGISTER_SOURCE_ICON} Title", "id": "Title"},
                        {"name": f"{REGISTER_SOURCE_ICON} Researchers", "id": "Researchers"},
                        {"name": f"{REGISTER_SOURCE_ICON} Datasets Used", "id": "Datasets Used"},
                        {"name": f"{REGISTER_SOURCE_ICON} Processing environment", "id": "Secure Research Service"},
                        {"name": f"{REGISTER_SOURCE_ICON} Accreditation Date", "id": "Accreditation Date"},
                        {"name": f"{DERIVED_FIELD_ICON} Domains", "id": "substantive_domains"},
                        {"name": f"{DERIVED_FIELD_ICON} Layer A domain count", "id": "substantive_domain_count"},
                        {"name": f"{DERIVED_FIELD_ICON} Linkage mode", "id": "linkage_mode"},
                        {"name": f"{DERIVED_FIELD_ICON} Purpose", "id": "analytical_purpose"},
                    ],
                    page_size=20,
                    sort_action="native",
                    filter_action="none",
                    **ENRICHED_TABLE_STYLES,
                ),
                className="dea-table mb-4",
            ),
        ]
    else:
        children = [
            dbc.Alert(
                "Thematic analysis data not available. Run analysis/llm_theme_analysis_v3.py to generate.",
                color="info", className="mt-3",
            ),
        ]

    return dbc.Tab(
        label="Thematic Analysis (Experimental)", tab_id="tab-thematic", children=children,
    )
