"""Aggregate-only reporting, provenance, notebook, and masking checks."""
from __future__ import annotations
import json,sys,platform,subprocess
from datetime import datetime,timezone
import numpy as np,pandas as pd,yaml,pytest
from analysis.scratch_coder_stage_a.load import read_manifest_csv
from .config import ROOT,OUT,RAW,BASE,HARD,CROSS,RAW_MOD,LF_MOD,SEED,ATTEMPTS
from .support import sha
def writecsv(name,rows):pd.DataFrame(rows).to_csv(OUT/name,index=False,lineterminator='\n')
def f(x):return 'CI NOT ESTIMABLE' if x is None or pd.isna(x) else f'{float(x):.3f}'
def audit(r):
 rows=[]
 def add(analysis,pop,dim,label,pair,measure,num,den,value,support,band,valid='',notes=''):
  rows.append({'analysis':analysis,'population':pop,'dimension':dim,'label_or_tag':label,'pair':pair,'measure':measure,'numerator':num,'denominator':den,'value':value,'support_n':support,'support_band':band,'interval_method':'bootstrap percentile Type-7' if valid!='' else 'not applicable','bootstrap_valid_n':valid,'notes':notes})
 for x in r['support']:add('label_support','baseline',x['dimension'],x['label'],'','human-majority support',x['baseline_human_majority_positive_n'],150,x['baseline_human_majority_prevalence'],x['baseline_human_majority_positive_n'],x['support_band'])
 for x in r['cont']:
  add('per_label_contingency','baseline',x['dimension'],x['label'],'','human prevalence',x['human_majority_positive_n'],x['baseline_n'],x['human_majority_prevalence'],x['human_majority_positive_n'],x['support_band'])
  add('per_label_contingency','baseline',x['dimension'],x['label'],'','model prevalence',x['model_positive_n'],x['baseline_n'],x['model_prevalence'],x['human_majority_positive_n'],x['support_band'])
  add('per_label_contingency','baseline',x['dimension'],x['label'],'','TP/FP/FN/TN',x['tp'],x['baseline_n'],'',x['human_majority_positive_n'],x['support_band'],'',f"TP={x['tp']}; FP={x['fp']}; FN={x['fn']}; TN={x['tn']}")
 for x in r['exact']:
  add('exact_set',x['population'],x['dimension'],'',x['pair'],'exact-set agreement',x['exact_match_n'],x['n_records'],x['exact_match_proportion'],'','',x['exact_match_bootstrap_valid_n'])
  add('jaccard',x['population'],x['dimension'],'',x['pair'],'mean record-level Jaccard','',x['n_records'],x['mean_jaccard'],'','',x['mean_jaccard_bootstrap_valid_n'],'Aggregate only; no record-level values saved.')
 for x in r['tag']:
  for m in ('raw_agreement','positive_agreement','negative_agreement','cohen_kappa','gwet_ac1','precision','recall','f1'):add('tag_diagnostic',x['population'],'Cross-cutting tag',x['tag'],'',m,'',x['n_records'],x[m],x['baseline_support_n'],x['support_band'],x[m+'_bootstrap_valid_n'],f"TP={x['tp']}; FP={x['fp']}; FN={x['fn']}; TN={x['tn']}")
 return rows
def methods():return '''# Scratch-coder Stage B methods

Frozen inputs were POST-028 REDCap export, POST-009 baseline, POST-011 hard case, POST-019 crosswalk, PRO-018, RED-036, RED-013, MOD-001 rc2 taxonomy and MOD-006 Fable 5 production output. Stage B calls Stage A's audited parsing, validation-included filtering, joins and canonical unordered `frozenset` representation, with restored restricted paths supplied only at load time. The baseline population is 150 records; the 75 hard cases are explicitly diagnostic, disagreement-enriched and non-representative. There were no structurally invalid responses, so structural-validity sensitivity is identical; the one exposure-flagged baseline project remains primary.

For every label independently, human support is positive iff at least two of A/B/C assign it. This labelwise reference is analytical, not adjudicated gold standard, and Purpose majority labels are not capped. Baseline support defines RARE (<10), LOW SUPPORT (10–29), and STANDARD (>=30). Rare Domain/Purpose labels retain contingency/prevalence counts only; kappa, precision, recall and F1 are withheld. Macro metrics are unweighted means over the fixed baseline-observed support>=10 Domain/Purpose label set. A macro replicate is conservatively undefined if any fixed eligible label metric is undefined, avoiding a changing label set.

Exact agreement is equality of the complete unordered set. Jaccard is intersection/union, with empty/empty=1. Binary orientation is reference=majority human and prediction=Fable: TP=both positive, FP=model-only, FN=human-only, TN=both negative. Precision=TP/(TP+FP), recall=TP/(TP+FN), F1=2PR/(P+R). Cohen kappa uses the conventional binary observed and marginal expected agreement. Tag raw agreement=(TP+TN)/N; positive agreement=2TP/(2TP+FP+FN); negative agreement=2TN/(2TN+FP+FN). Binary two-rater Gwet AC1 uses Po, p=(p_A+p_B)/2, Pe=2p(1-p), AC1=(Po-Pe)/(1-Pe).

Bootstrap resampling uses 2,000 record-level samples, seed 20260714, keeping linked A/B/C/L values together and preserving duplicate draws. Related metrics use shared deterministic draws. Percentile intervals are 2.5/97.5 Hyndman–Fan Type 7 (linear). Undefined replicate values are excluded only for that statistic; an interval is `CI NOT ESTIMABLE` below ceil(0.90*attempts)=1800 valid replicates. No source IDs, titles, record-level values, FP/FN lists, disagreement cases, or adjudication population are output. Rare-label examples and adjudicated issue notes are deferred until adjudication to preserve masking.
'''
def summary(r):
 s=pd.DataFrame(r['support']);c=pd.DataFrame(r['cont']);p=pd.DataFrame(r['perf']);e=pd.DataFrame(r['exact']);m=pd.DataFrame(r['macro']);t=pd.DataFrame(r['tag']);L=['# Scratch-coder Stage B summary','', 'Preliminary Stage B aggregate diagnostics from the frozen scratch-coder validation dataset. Record-level disagreement adjudication and project-owner evidence are not incorporated.','','## Support distribution','','Support is determined only from two-of-three majority-human positives in the 150-record random baseline.']
 for b,title in [('RARE','<10'),('LOW SUPPORT','10–29'),('STANDARD','>=30')]:
  L+=['',f'### {title}']+[f"- {x.dimension}: {x.label} (N={x.baseline_human_majority_positive_n})" for x in s[s.support_band==b].sort_values(['dimension','label']).itertuples()]
 L+=['','## Exact-set / Jaccard']
 for pop in ('baseline','hard_case'):
  L+=['',f'### {pop}'+(' — DIAGNOSTIC — disagreement-enriched and non-representative.' if pop=='hard_case' else ''),'','| Dimension | Pair | Exact-set [95% CI] | Mean Jaccard [95% CI] |','|---|---|---:|---:|']
  for x in e[e.population==pop].itertuples():L.append(f'| {x.dimension} | {x.pair} | {f(x.exact_match_proportion)} [{f(x.exact_match_ci_lower)}, {f(x.exact_match_ci_upper)}] | {f(x.mean_jaccard)} [{f(x.mean_jaccard_ci_lower)}, {f(x.mean_jaccard_ci_upper)}] |')
 for dim,name in [('Research Domains','Domain'),('Analytical Purposes','Purpose')]:
  L+=['',f'## Per-label {name} diagnostics','','| Label | Human N | Model N | Band | Precision [95% CI] | Recall [95% CI] | F1 [95% CI] |','|---|---:|---:|---|---:|---:|---:|']
  for x in c[c.dimension==dim].itertuples():
   z=p[(p.dimension==dim)&(p.label==x.label)]
   if z.empty:L.append(f'| {x.label} | {x.human_majority_positive_n} | {x.model_positive_n} | {x.support_band} | DESCRIPTIVE ONLY — performance estimates withheld under preregistered rare-label rule. | DESCRIPTIVE ONLY | DESCRIPTIVE ONLY |')
   else:
    y=z.iloc[0];L.append(f'| {x.label} | {x.human_majority_positive_n} | {x.model_positive_n} | {x.support_band} | {f(y.precision)} [{f(y.precision_ci_lower)}, {f(y.precision_ci_upper)}] | {f(y.recall)} [{f(y.recall_ci_lower)}, {f(y.recall_ci_upper)}] | {f(y.f1)} [{f(y.f1_ci_lower)}, {f(y.f1_ci_upper)}] |')
  L.append('Pairwise A-B/A-C/B-C/L-A/L-B/L-C kappa is provided in `per_label_pairwise_kappa.csv`. Record examples and adjudicated issue notes for rare labels are deferred until adjudication in order to preserve record-level masking.')
 L+=['','## Macro performance']
 for x in m.itertuples():L.append(f'- {x.dimension}: eligible labels: {x.eligible_labels}; precision {f(x.precision)} [{f(x.precision_ci_lower)}, {f(x.precision_ci_upper)}], recall {f(x.recall)} [{f(x.recall_ci_lower)}, {f(x.recall_ci_upper)}], F1 {f(x.f1)} [{f(x.f1_ci_lower)}, {f(x.f1_ci_upper)}].')
 L+=['','## Tag diagnostics']
 for x in t.itertuples():
  low=' **LOW SUPPORT — estimates are unstable and should not be interpreted from point estimates alone.**' if x.low_support_caution else ''
  L+=['',f'### {x.tag} — {x.population}'+(' — DIAGNOSTIC — disagreement-enriched and non-representative.' if x.population=='hard_case' else '')+low,f'Support {x.baseline_support_n} ({x.support_band}); human prevalence {f(x.human_majority_prevalence)}; model prevalence {f(x.model_prevalence)}.',f'Raw {f(x.raw_agreement)} [{f(x.raw_agreement_ci_lower)}, {f(x.raw_agreement_ci_upper)}]; positive {f(x.positive_agreement)} [{f(x.positive_agreement_ci_lower)}, {f(x.positive_agreement_ci_upper)}]; negative {f(x.negative_agreement)} [{f(x.negative_agreement_ci_lower)}, {f(x.negative_agreement_ci_upper)}]; kappa {f(x.cohen_kappa)} [{f(x.cohen_kappa_ci_lower)}, {f(x.cohen_kappa_ci_upper)}]; AC1 {f(x.gwet_ac1)} [{f(x.gwet_ac1_ci_lower)}, {f(x.gwet_ac1_ci_upper)}]; precision {f(x.precision)} [{f(x.precision_ci_lower)}, {f(x.precision_ci_upper)}]; recall {f(x.recall)} [{f(x.recall_ci_lower)}, {f(x.recall_ci_upper)}]; F1 {f(x.f1)} [{f(x.f1_ci_lower)}, {f(x.f1_ci_upper)}].']
 L+=['','## Interpretation boundary','','The majority-human reference is a preregistered analytical device for per-label metrics and later adjudication eligibility. It is not an adjudicated gold standard.','','Hard-case records are disagreement-enriched and are not used for population-level per-label performance estimation or support thresholds.','','Labels with fewer than 10 majority-human-positive baseline records are reported descriptively only.','','Stage B reveals aggregate label-specific performance patterns but does not identify the records producing those patterns.','','Record examples and adjudicated issue notes are deferred until adjudication.']
 return '\n'.join(L)+'\n'
def notebook():
 def cell(kind,source):return {'cell_type':kind,'metadata':{},'source':source.splitlines(True),'outputs':[],'execution_count':None} if kind=='code' else {'cell_type':kind,'metadata':{},'source':source.splitlines(True)}
 cells=[cell('markdown','# Scratch-coder Stage B aggregate review'),cell('code',"from pathlib import Path\nimport sys\nROOT=Path.cwd().resolve()\nwhile ROOT != ROOT.parent and not (ROOT/'.git').exists(): ROOT=ROOT.parent\nif not (ROOT/'.git').exists(): raise RuntimeError('Repository root not found')\nsys.path.insert(0,str(ROOT))\nimport json,pandas as pd,numpy as np\nfrom analysis.scratch_coder_stage_a import validate_export\nfrom analysis.scratch_coder_stage_b import build_stage_b_data,run_stage_b_analysis\nfrom analysis.scratch_coder_stage_b.metrics import prf,tagstats,kappa\nfrom analysis.validation.bootstrap import percentile\nOUT=ROOT/'analysis/outputs_validation_scratch_stage_b_20260825'"),cell('markdown','## 1. Frozen authorities / hashes\n## 2. Panel reconciliation\n## 3. Label support\n## 4. Exact-set agreement\n## 5. Jaccard\n## 6. Per-label contingencies\n## 7. Per-label pairwise kappa\n## 8. Model precision/recall/F1\n## 9. Macro performance\n## 10. Tag diagnostics'),cell('code',"meta=json.loads((OUT/'run_metadata.json').read_text()); data=build_stage_b_data(); assert (len(data.responses),len(data.baseline_ids),len(data.hard_case_ids))==(675,150,75)\nsupport=pd.read_csv(OUT/'label_support.csv'); exact=pd.read_csv(OUT/'exact_set_jaccard_summary.csv'); cont=pd.read_csv(OUT/'per_label_contingencies.csv'); kap=pd.read_csv(OUT/'per_label_pairwise_kappa.csv'); perf=pd.read_csv(OUT/'per_label_model_performance.csv'); macro=pd.read_csv(OUT/'macro_performance.csv'); tags=pd.read_csv(OUT/'tag_diagnostics.csv')\n(meta['verified_authorities'],support,exact,cont,kap,perf,macro,tags)"),cell('markdown','## 11. Bootstrap checks\n## 12. Assertions against saved output CSVs'),cell('code',"r=perf.iloc[0]; c=cont[(cont['dimension']==r['dimension'])&(cont['label']==r['label'])].iloc[0]; z=prf({'tp':int(c.tp),'fp':int(c.fp),'fn':int(c.fn),'tn':int(c.tn)}); assert all(np.isclose(z[k],r[k]) for k in z)\nt=tags.iloc[0]; ref=[1]*int(t.tp)+[0]*int(t.fp)+[1]*int(t.fn)+[0]*int(t.tn); pred=[1]*int(t.tp)+[1]*int(t.fp)+[0]*int(t.fn)+[0]*int(t.tn); assert np.isclose(tagstats(ref,pred)['gwet_ac1'],t.gwet_ac1)\nb=pd.read_csv(OUT/'bootstrap_per_label_performance.csv');v=b[(b['dimension']==r['dimension'])&(b['label']==r['label'])].precision.dropna().tolist();assert np.isclose(percentile(v,.025),r.precision_ci_lower);assert np.isclose(percentile(v,.975),r.precision_ci_upper)\nassert len(exact)==12 and set(kap['pair'])=={'A-B','A-C','B-C','L-A','L-B','L-C'}")]
 (OUT/'scratch_coder_stage_b_review.ipynb').write_text(json.dumps({'cells':cells,'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python'}},'nbformat':4,'nbformat_minor':5},indent=1)+'\n',encoding='utf-8')
def scan(data):
 model=read_manifest_csv('MOD-006');titles=set(model.loc[model['Record ID'].isin(data.formal_ids),'Title'].astype(str))-{''};text='\n'.join(x.read_text(encoding='utf-8',errors='ignore') for x in OUT.iterdir() if x.is_file());bad={'real_source_ids_detected':sum(x in text for x in data.formal_ids),'project_titles_detected':sum(x in text for x in titles),'record_level_disagreement_outputs':sum((OUT/x).exists() for x in ('adjudication_population.csv','disagreement_records.csv','false_positive_records.csv','false_negative_records.csv','majority_vs_model_by_record.csv','model_errors.csv'))};
 if any(bad.values()):raise RuntimeError(f"Mask scan failed: {sum(bad.values())} prohibited matches")
 return bad
